import { Nav } from '@/components/Nav';
import { AboutMap } from '@/components/AboutMap';
import { achievements, education, experiences, skillGroups } from '@/content/about-data';

function emphasize(text: string) {
  return text.split(/(\d[\d+,.%]*(?:\s?(?:million|minutes|global regions|distributed servers|domains|students))?|ACL|NAACL|14 million transactions per month|AI agents|80\+ custom agentic AI workflows)/gi).map((part, index) => /^(\d|ACL$|NAACL$|AI agents$|80\+)/i.test(part) ? <strong key={index} className="font-bold text-ink">{part}</strong> : part);
}

const sectionTitle = (title: string) => <div className="mb-8"><h2 id={{ 'Professional experience': 'experience-title', 'Education & training': 'education-title', Skills: 'skills-title' }[title]} className="font-display text-4xl tracking-[-0.04em] text-ink sm:text-5xl">{title}</h2></div>;

export default function About() {
  return <main className="mx-auto max-w-7xl px-6 sm:px-10 lg:px-16">
    <Nav />
    <header className="pb-8 pt-12 sm:pt-16"><h1 className="mb-6 font-display text-5xl tracking-[-0.055em] text-ink sm:text-6xl">About Me & My Work</h1><p className="text-base leading-8 text-ink/70">I am an enthusiastic builder and researcher focused on creating explainable and trustworthy AI systems, with a core research goal of developing reliable, data-driven solutions to pressing societal challenges. Alongside research and software development, I enjoy badminton, football, and sports analytics. Beyond computers, I am pursuing my interests in languages and working toward becoming a certified pilot.</p><p className="mt-5 text-base leading-8 text-ink/70">My work is best represented by this living record of the places, people, and questions shaping my academic and professional journey.</p></header>
    <section aria-label="My research and achievement map" className="pb-16"><AboutMap achievements={achievements} /></section>
    <section className="border-t border-ink/10 py-16" aria-labelledby="experience-title">{sectionTitle('Professional experience')}<div className="space-y-8">{experiences.map((experience) => <article key={`${experience.company}-${experience.role}`} className="grid gap-3 sm:grid-cols-[minmax(170px,0.6fr)_minmax(0,1.4fr)] sm:gap-10"><div><p className="text-sm font-bold text-ink">{experience.company}</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.08em] text-sky">{experience.role}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-ink/45">{experience.dates} · {experience.location}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-ink/70">{experience.bullets.map((bullet) => <li key={bullet} className="relative pl-4 before:absolute before:left-0 before:top-[0.7em] before:h-1 before:w-1 before:rounded-full before:bg-coral">{emphasize(bullet)}</li>)}</ul></div></article>)}</div></section>
    <section className="border-t border-ink/10 py-16" aria-labelledby="education-title">{sectionTitle('Education & training')}<div className="space-y-8">{education.map((item) => <article key={item.degree} className="grid gap-3 sm:grid-cols-[minmax(170px,0.6fr)_minmax(0,1.4fr)] sm:gap-10"><div><h3 className="text-sm font-bold text-ink">{item.degree}</h3><p className="mt-1 text-xs leading-5 text-sky">{item.institution}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-ink/45">{item.dates}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-ink/70">{item.bullets.map((bullet) => <li key={bullet} className="relative pl-4 before:absolute before:left-0 before:top-[0.7em] before:h-1 before:w-1 before:rounded-full before:bg-coral">{emphasize(bullet)}</li>)}</ul></div></article>)}</div></section>
    <section className="border-t border-ink/10 py-16" aria-labelledby="skills-title">{sectionTitle('Skills')}<div className="grid gap-x-12 gap-y-7 sm:grid-cols-2 lg:grid-cols-3">{skillGroups.map((group) => <div key={group.category}><h3 className="text-sm font-bold text-ink">{group.category}</h3><div className="mt-3 flex flex-wrap gap-2">{group.skills.map((skill) => <span key={skill} className="rounded-full border border-ink/10 bg-white/45 px-3 py-1.5 text-xs text-ink/65">{skill}</span>)}</div></div>)}</div></section>
    <footer className="flex items-center justify-between border-t border-ink/10 py-7 text-[10px] font-semibold uppercase tracking-[0.16em] text-ink/40"><span>Sahil Kale</span><span>Research with care</span></footer>
  </main>;
}
